<?php
// php/admin_save_doctor.php
// Creates or updates a doctor profile
// Called by admin-doctors.html page
require_once 'config.php';

// Only admin can access this endpoint
require_role('admin');

// Get JSON input from request body
$input = json_decode(file_get_contents('php://input'), true);

// Validate required fields
// doctor_id is optional - if provided, we update existing doctor; if not, we create new one
$doctor_id = $input['doctor_id'] ?? null;
$dept_id = $input['dept_id'] ?? null;
$full_name = $input['full_name'] ?? null;
$specialization = $input['specialization'] ?? null;
$bio = $input['bio'] ?? null;
$is_active = $input['is_active'] ?? 1;

// Basic validation
if (!$dept_id || !$full_name) {
    send_json(['error' => 'Department and full name are required.'], 400);
}

try {
    $pdo->beginTransaction();

    if ($doctor_id) {
        // UPDATE existing doctor
        // Logic: Update the doctor record with new values
        // We preserve the doctor_id but can change all other fields
        $stmt = $pdo->prepare("
            UPDATE doctors
            SET dept_id = :dept_id,
                full_name = :full_name,
                specialization = :specialization,
                bio = :bio,
                is_active = :is_active
            WHERE doctor_id = :doctor_id
        ");
        $stmt->execute([
            ':dept_id' => $dept_id,
            ':full_name' => $full_name,
            ':specialization' => $specialization,
            ':bio' => $bio,
            ':is_active' => $is_active,
            ':doctor_id' => $doctor_id
        ]);

    } else {
        // CREATE new doctor
        // Logic: Insert a new doctor record with the provided information
        // doctor_id is auto-generated by the database
        $stmt = $pdo->prepare("
            INSERT INTO doctors (dept_id, full_name, specialization, bio, is_active)
            VALUES (:dept_id, :full_name, :specialization, :bio, :is_active)
        ");
        $stmt->execute([
            ':dept_id' => $dept_id,
            ':full_name' => $full_name,
            ':specialization' => $specialization,
            ':bio' => $bio,
            ':is_active' => $is_active
        ]);
    }

    $pdo->commit();
    send_json(['success' => true, 'message' => $doctor_id ? 'Doctor updated successfully' : 'Doctor created successfully']);

} catch (PDOException $e) {
    $pdo->rollBack();
    error_log('[HAMS] Error saving doctor: ' . $e->getMessage());
    send_json(['error' => 'Failed to save doctor', 'detail' => $e->getMessage()], 500);
}
?>
